server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: spring-boot-task-manager
  
  # データベース設定
  datasource:
    url: jdbc:h2:mem:taskdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
    
  # H2 Console設定
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
        
  # JPA/Hibernate設定
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
    
  # SQL初期化設定
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      
  # Jackson JSON設定
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Tokyo

# Swagger/OpenAPI設定
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    default-models-expand-depth: 1
    default-model-expand-depth: 1
  show-actuator: false
  paths-to-match:
    - /api/**

# ログ設定
logging:
  level:
    com.taskmanager: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    
# 開発環境設定
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 